### ISSUE TITLE
Game bugs [which are not caused by us]

### ISSUE THREAD

**Issue by Lezor91** [rs-peer/inuvation#8]
## The game fails to enter DirectX or OpenGL mode
**Workaround:** Load Inuvation with JRE instead of JDK
**Solution:** ^
**Status**: Unresolved

## Font loading in Safe Mode
_The Safe Mode renderers font loader fails to load certain fonts and may lead to game crashes._ 
**Workaround:** Use DirectX or OpenGL
**Solution:** Inject a patch

## UnsupportedOperationException on ProxySelector
_In newer Java versions a certain method was changed to return an immutable collection, the game client relies on adding to that collection_
**Workaround:** Use Java 8
**Solution:** Override the ProxySelector

**Comment by SPEN-CER** [comment]
This seems to be resolved besides entering native render modes which still seems to be a bit troublesome but can be revisited at a later point
